# -*- coding: utf-8 -*-
"""scorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jp7_zLs6_wn7qyyoz-OQ3t5UCgcJv7V2
"""

import json
import logging
from typing import List, Dict, Any

# Configure logging for professional output
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class ClipScorer:
    """
    Analyzes transcription segments and assigns an engagement score
    based on keyword presence and optimal sentence length.
    """
    def __init__(self, optimal_duration: float = 15.0):
        self.optimal_duration = optimal_duration

        # High-engagement keywords to look for in the text
        self.high_impact_keywords = {
            "important", "secret", "reason", "why", "how", "best",
            "worst", "never", "always", "discover", "money", "hack",
            "truth", "rule", "stop", "start", "today", "listen"
        }

    def _score_keywords(self, text: str) -> float:
        """Calculates a score based on the presence of high-impact keywords."""
        words = text.lower().split()
        if not words:
            return 0.0

        keyword_count = sum(1 for word in words if word.strip('.,!?') in self.high_impact_keywords)
        # Max out keyword score at 5.0 (assuming 1 point per keyword)
        return min(keyword_count * 1.5, 5.0)

    def _score_length(self, start: float, end: float) -> float:
        """
        Calculates a score based on how close the segment duration
        is to the optimal Short duration (e.g., 15 seconds).
        """
        duration = end - start

        # Too short (under 3s) or too long (over 60s) gets heavily penalized
        if duration < 3.0 or duration > 60.0:
            return 0.0

        # The closer to the optimal duration, the higher the score (max 5.0)
        deviation = abs(self.optimal_duration - duration)
        score = max(5.0 - (deviation * 0.3), 0.0)

        return score

    def score_segments(self, transcript_data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Iterates through the transcript segments, calculates scores,
        and appends the score to each segment.
        """
        scored_segments = []

        for segment in transcript_data:
            text = segment.get("text", "")
            start = segment.get("start", 0.0)
            end = segment.get("end", 0.0)

            # Calculate individual scores
            kw_score = self._score_keywords(text)
            len_score = self._score_length(start, end)

            # Total score (out of 10)
            total_score = round(kw_score + len_score, 2)

            # Create a new dictionary to avoid modifying the original
            scored_segment = segment.copy()
            scored_segment["engagement_score"] = total_score
            scored_segments.append(scored_segment)

        # Sort segments by highest score first
        scored_segments.sort(key=lambda x: x["engagement_score"], reverse=True)
        return scored_segments

def process_transcript(input_json_path: str, output_json_path: str) -> None:
    """Main function to load the transcript, score it, and save the results."""
    try:
        with open(input_json_path, 'r', encoding='utf-8') as f:
            transcript = json.load(f)

        # Handle standard faster-whisper structure
        segments = transcript.get("segments", []) if isinstance(transcript, dict) else transcript

        scorer = ClipScorer()
        logging.info(f"Scoring {len(segments)} segments...")

        scored_data = scorer.score_segments(segments)

        # Save the scored output
        with open(output_json_path, 'w', encoding='utf-8') as f:
            json.dump({"scored_segments": scored_data}, f, indent=4)

        logging.info(f"Successfully scored segments and saved to {output_json_path}")

    except FileNotFoundError:
        logging.error(f"Could not find the input file: {input_json_path}")
    except Exception as e:
        logging.error(f"An error occurred: {str(e)}")

# This block allows you to run the file directly for testing
if __name__ == "__main__":
    process_transcript("transcript.json", "scored_transcript.json")