# -*- coding: utf-8 -*-
"""subtitle_export.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jp7_zLs6_wn7qyyoz-OQ3t5UCgcJv7V2
"""

import json
import logging
from datetime import timedelta

# Configure logging for professional output
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def format_timestamp(seconds: float) -> str:
    """
    Converts a float representing seconds into the standard SRT
    timestamp format: HH:MM:SS,mmm
    """
    td = timedelta(seconds=seconds)

    # Calculate hours, minutes, seconds, and milliseconds
    total_seconds = int(td.total_seconds())
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    seconds = total_seconds % 60

    # Extract milliseconds and format to 3 digits
    milliseconds = int((td.total_seconds() - total_seconds) * 1000)

    return f"{hours:02}:{minutes:02}:{seconds:02},{milliseconds:03}"

def export_to_srt(json_path: str, srt_path: str) -> None:
    """
    Reads a transcript JSON file and exports it as an SRT subtitle file.
    """
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Handle standard faster-whisper structure
        segments = data.get("segments", []) if isinstance(data, dict) else data

        with open(srt_path, 'w', encoding='utf-8') as f:
            for index, segment in enumerate(segments, start=1):
                # Format timestamps
                start_time = format_timestamp(segment.get("start", 0.0))
                end_time = format_timestamp(segment.get("end", 0.0))

                # Clean the text
                text = segment.get("text", "").strip()

                # Write to file in strict SRT format
                f.write(f"{index}\n")
                f.write(f"{start_time} --> {end_time}\n")
                f.write(f"{text}\n\n")

        logging.info(f"Successfully generated subtitles at: {srt_path}")

    except FileNotFoundError:
        logging.error(f"Could not find the input file: {json_path}")
    except Exception as e:
        logging.error(f"An error occurred during SRT export: {str(e)}")

# Execution block for testing
if __name__ == "__main__":
    # Ensure you have a valid transcript.json in the same directory to test
    export_to_srt("transcript.json", "output.srt")